services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
    networks:
      - internal
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
     - "4317:4317"   # OTLP gRPC receiver
     - "4318:4318"   # OTLP HTTP receiver
    networks:
      - internal
  chroma:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "1234:8000"
    networks:
      - internal
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4317/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
      - ALLOW_RESET=TRUE
      - CHROMA_SERVER_ALLOW_RESET=TRUE
    depends_on:
      - otel-collector
      - zipkin

networks:
  internal:

volumes:
  chroma_data:
