receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [otlp] # otlp receiver will send the data to traces pipeline
      exporters: [zipkin, debug] # define that telemetry data is logged to the console (debug) and sent to Zipkin server
    metrics: # otlp receiver will also send the data to metrics pipeline
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]